name: NPM Package Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/lib/**'
      - '.github/workflows/npm-publish.yml'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./frontend/lib
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@chess3001'

      - name: Install dependencies
        run: |
          npm ci
          npm install --no-package-lock --no-save rollup-plugin-postcss
          
      - name: Build package
        run: |
          npm run build
          
      - name: Publish to GitHub Packages
        if: github.event_name != 'pull_request'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
